# Generated by Django 5.0.4 on 2024-04-27 10:53

import accounts.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", accounts.managers.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="useremailmodel",
            name="is_password",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userphonenumbermodel",
            name="is_password",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="useremailmodel",
            name="security_code",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="useremailmodel",
            name="sent_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="userphonenumbermodel",
            name="security_code",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="userphonenumbermodel",
            name="sent_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
